[workspace]
members = ["vpi", "vpi-sys", "examples/siminfo", "examples/timescale", "examples/dumper"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"


[workspace.dependencies]
bindgen = "0.72.1"
bitflags = "2"
num-traits = "0.2"
num-derive = "0.4"
vpi-sys = { path = "vpi-sys" }
vpi = { path = "vpi" }
